name: mi_weather
description: Weather app for you

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.1.1
  cupertino_icons: ^1.0.2
  date_time_format: ^2.0.1
  dio: ^4.0.0
 
  font_awesome_flutter: ^9.0.0
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  http: ^0.13.1
  intl: ^0.17.0
  logger: ^1.0.0
  oktoast: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
