name: mi_weather
description: Weather app for you

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  font_awesome_flutter: ^9.0.0
  get: ^4.1.1
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  http: ^0.13.1
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
